export const variants = [
	'bodyMedium',
	'bodyRegular',
	'captionMedium',
	'descriptionMedium',
	'descriptionRegular',
	'footerMedium',
	'h3SemiBold',
	'h3Medium',
	'headingMedium',
	'headingSemiBold',
	'subHeadingSemiBold',
	'subHeadingMedium',
	'subHeadingRegular',
	'superTitleSemiBold',
	'superTitleMedium',
	'tagMedium',
	'titleSemiBold',
	'titleMedium',
] as const;
